### ISSUE TITLE
lib/slick-util.jar missing

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [parzivail/StarWarsGalaxy#3]
But please try to use a Maven dependency instead of copying binary files to the repository.

**Comment by parzivail** [comment]
This repo, as of right now, is just a clone of my working directory. Give me a few days to get everything worked out to make a better development experience.

**Comment by kaeptmblaubaer1000** [comment]
https://gist.github.com/kaeptmblaubaer1000/6bb6a072a3e7f16c2960f6a7e8fc6232

**Comment by kaeptmblaubaer1000** [comment]
@parzivail is it [this](https://github.com/parzivail/StarWarsGalaxy/files/2438668/slick-util.jar.zip) file?

**Comment by parzivail** [comment]
Correct. I'll add it as a maven dep as I finish the build instructions.

**Comment by parzivail** [comment]
It seems that the library isn't tracked in the repo, so I'll just add it as a maven dep like I originally thought.
