### ISSUE TITLE
deobfmod.bat not working

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [parzivail/StarWarsGalaxy#6]
I'd recommend you to replace it with a `JavaExec` Gradle task or removing it.
It doesn't work because you removed `simpledeobf-0.6.jar` and you assume that the Windows drive letter is "C" and the user name is "Administrator".

**Comment by parzivail** [comment]
You shouldn't need to use that as it was an internal testing tool for a different project that found it's way into this repo. I'll remove it as well.
